@testset "Piece" begin
    @test ispromotable(PAWN) == true
    @test ispromotable(LANCE) == true
    @test ispromotable(KNIGHT) == true
    @test ispromotable(SILVER) == true
    @test ispromotable(GOLD) == false
    @test ispromotable(KING) == false
    @test ispromotable(BISHOP) == true
    @test ispromotable(ROOK) == true
    @test ispromotable(PROMOTED_PAWN) == false
    @test ispromotable(PROMOTED_LANCE) == false
    @test ispromotable(PROMOTED_KNIGHT) == false
    @test ispromotable(PROMOTED_SILVER) == false
    @test ispromotable(PROMOTED_BISHOP) == false
    @test ispromotable(PROMOTED_ROOK) == false
    @test isunpromotable(PAWN) == false
    @test isunpromotable(LANCE) == false
    @test isunpromotable(KNIGHT) == false
    @test isunpromotable(SILVER) == false
    @test isunpromotable(GOLD) == false
    @test isunpromotable(KING) == false
    @test isunpromotable(PROMOTED_PAWN) == true
    @test isunpromotable(PROMOTED_LANCE) == true
    @test isunpromotable(PROMOTED_KNIGHT) == true
    @test isunpromotable(PROMOTED_SILVER) == true
    @test isunpromotable(PROMOTED_BISHOP) == true
    @test isunpromotable(PROMOTED_ROOK) == true
    @test Shogi.promote(PAWN) == PROMOTED_PAWN
    @test Shogi.promote(LANCE) == PROMOTED_LANCE
    @test Shogi.promote(KNIGHT) == PROMOTED_KNIGHT
    @test Shogi.promote(SILVER) == PROMOTED_SILVER
    @test Shogi.promote(GOLD) == GOLD
    @test Shogi.promote(KING) == KING
    @test Shogi.promote(BISHOP) == PROMOTED_BISHOP
    @test Shogi.promote(ROOK) == PROMOTED_ROOK
    @test Shogi.promote(PROMOTED_PAWN) == PROMOTED_PAWN
    @test Shogi.promote(PROMOTED_LANCE) == PROMOTED_LANCE
    @test Shogi.promote(PROMOTED_KNIGHT) == PROMOTED_KNIGHT
    @test Shogi.promote(PROMOTED_SILVER) == PROMOTED_SILVER
    @test Shogi.promote(PROMOTED_BISHOP) == PROMOTED_BISHOP
    @test Shogi.promote(PROMOTED_ROOK) == PROMOTED_ROOK
    @test unpromote(PAWN) == PAWN
    @test unpromote(LANCE) == LANCE
    @test unpromote(KNIGHT) == KNIGHT
    @test unpromote(SILVER) == SILVER
    @test unpromote(GOLD) == GOLD
    @test unpromote(KING) == KING
    @test unpromote(BISHOP) == BISHOP
    @test unpromote(ROOK) == ROOK
    @test unpromote(PROMOTED_PAWN) == PAWN
    @test unpromote(PROMOTED_LANCE) == LANCE
    @test unpromote(PROMOTED_KNIGHT) == KNIGHT
    @test unpromote(PROMOTED_SILVER) == SILVER
    @test unpromote(PROMOTED_BISHOP) == BISHOP
    @test unpromote(PROMOTED_ROOK) == ROOK
end